databases:
  - name: sqlite3
    plan: free
    databaseName: db.sqlite3
    user: root

services:
  - type: web
    plan: free
    name: eventex
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn eventex.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db.sqlite3
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
